### PR TITLE
New autolayout utilities. Partial cleanup of SnapKit use

### PR DESCRIPTION
**Pull request by omoralesvivo**
WHY:

We aim to minimize third party dependencies for Thumbprint, SnapKit is an obvious target and it was agreed a while ago to clean it up.

WHAT:

- Filled out the auto layout utilities in `UIView+Layout.swift`. They seem to cover most of the drudgery, what's left is fine to do with the auto layout anchor API or too rare/obscure to bother wrapping.
  - New `UIView.addManagedSubview` wrapper that sets `translatesAutoresizingMaskIntoConstraints = false` when adding a subview. Once migration off SnapKit is complete we can add a SwiftLint rule to avoid use of vanilla `addSubview` which should basically remove the need to manually set `translatesAutoresizingMaskIntoConstraints = false` in UI buildup logic.
  - New centering in subview utility
  - Generalized utilities into common logic and added additional tests.
- Fully removed SnapKit use from Thumbprint tests.
- Partially removed SnapKit use from Thumbprint components. Also applied new utilities in files cleaned of SnapKit.
- Podfile modified as to limit the SnapKit dependency to the Thumbprint target.

TESTING:

- CI should verify that everything lays out the same as before.
- Also some new unit tests for the new auto layout utilities.

### CODE REVIEW

**Comment by dwroth** [comment]
Would you mind elaborating on the motivation for this?  Personally I don't agree that every 3rd party dependency should be replaced with in house code.  Unless we have identified an actual problem that we need to work around, why are we trying to reinvent the wheel here?

**Comment by omoralesvivo** [comment]
We already had this debate last year and this is the decision we ended up going for as a team. I understand that it's taken me a while to get to it but I'd rather not repeat the debate again.

**Comment by dwroth** [comment]
Could you at least link me to the debate? I clearly wasn't a part of it....

**Comment by omoralesvivo** [comment]
This was the RFC for the debate. And yes you were a part of it, that's why I added you to the review list.

**Comment by dwroth** [comment]
Looking at that RFC, I'm certainly not seeing any sort of universal agreement in the comments.  I'd be curious to see what other people have to say on the issue, but I stand pretty firmly in the camp of SnapKit being a welcome convenience.  And calling SnapKit a point of friction is a bit dramatic – the documentation is a short 8 page (at 16pt font, 25.6 line height). Cobalt, Tophat, and V1 endpoints are such significantly larger points of friction, that I would hardly even count SnapKit as significant, especially given it's human readable syntax (e.g. `make.edges.equalToSuperView()`)

**Comment by omoralesvivo** [comment]
We already had this debate where you said pretty much the same things. I guess I'll have to find the time to find where we left the resolution in writing or alternatively just dump the PR.

**Comment by dwroth** [comment]
I just want to be sure that we have some team consensus before we commit to this path.  That's all.

**Pull request closed without merging**
