### PR TITLE
XCode 13 Upgrade

### PR DESCRIPTION
**Pull request by scottasoutherland**
Upgrade to XC 13

### CODE REVIEW

**Comment by scottasoutherland** [comment]
The main thing here is the change to the navigation bar & the tab bar. Effectively those should translate into no real visible changes, however, it is required because as of iOS 15 defaults the "scroll edge appearance" to be transparent unless you set it, effectively forcing us to convert to the new api.

**Review by Abdul-Moiz — APPROVED** [review]
😱 OMG! the amount of code required to modify the tabBar and navigationBar appearances. 

Looked at the swift files. It's looking good. For the snapshots looked at random ones from all possible test cases which also seems good.

**Comment by Abdul-Moiz** [comment]
Also, navigation bar snapshots seems broken. Back icon is flipped horizontally. Kindly look into that. Just checked the snapshots.

**Comment by scottasoutherland** [comment]
> Also, navigation bar snapshots seems broken. Back icon is flipped horizontally. Kindly look into that. Just checked the snapshots.

This is how it was before, and it's just because the test *specifies* that icon: https://github.com/thumbtack/thumbprint-ios/blob/4a4e5c3196efc085fc799d85243faccf78a0b5f3/Thumbprint/Targets/ThumbprintTests/Snapshot/Components/NavigationBarTest.swift#L43

i can change it to caret-left-medium if you like ?

**Comment by Abdul-Moiz** [comment]
Please update it. Otherwise not just me but others will also feel like navigation bar is broken in XC13 😅

**Comment by scottasoutherland** [comment]
> Please update it. Otherwise not just me but others will also feel like navigation bar is broken in XC13 😅

Done

**Comment by scottasoutherland** [comment]
github is being super shitty right now and not letting me merge because it's confused and thinks it needs to run actions for iOS 14.5 and 15.0 ...but not running 14.5...because the original file had 14.5

**Comment by scottasoutherland** [comment]
And the admin override is not working, so i might have to push straight to master

**Pull request closed without merging**
