### PR TITLE
Use the official lint plugin

### PR DESCRIPTION
**Pull request by Muhieddine-El-Kaissi**
The third party lint plugin doesn't seem to work  in the main app
```
Error while creating cache: You don’t have permission to save the file “9030F0EF-F3AB-3361-A5B2-BC9D54BAEAA1” in the folder “0.52.2”.
Linting Swift files at paths ...
Error: No lintable files found at paths: ...
```

### CODE REVIEW

**Comment by scottasoutherland** [comment]
Is this a limitation of github actions or does this not work locally as well ?

**Comment by Muhieddine-El-Kaissi** [comment]
> Is this a limitation of github actions or does this not work locally as well ?

it doesn't work locally too :(

**Comment by scottasoutherland** [comment]
Any idea what the difference is between this and the thumbtack iOS repo ?

**Comment by Muhieddine-El-Kaissi** [comment]
> Any idea what the difference is between this and the thumbtack iOS repo ?

in the main repo we use xcode to add the plugin to build phase. in here it's defined in the package.swift. I think this flag --allow-writing-to-package-directory may not be active in the main repo or most possible because it's a dependency from this package so we can't write on it

**Review by scottasoutherland — APPROVED** [review]

**Pull request merged**
