### PR TITLE
Adding Support for Seasonal Icons

### PR DESCRIPTION
**Pull request by jmittelstaedt12**
We have some new seasonal icons in the meta category that design would like supported in thumbprint. [iOS PR link](https://github.com/thumbtack/ios/pull/12349)

### CODE REVIEW

**Review by Abdul-Moiz — COMMENTED** [review]
I am confused here, since these icons will be available as public resource shouldn't they also be included in this project?

**Comment by dwroth** [comment]
@Abdul-Moiz  the icons themselves aren't public. That's why you have to log in via okta to see them on thumbprint.design

**Comment by Abdul-Moiz** [comment]
> @Abdul-Moiz the icons themselves aren't public. That's why you have to log in via okta to see them on thumbprint.design

That is my concern that someone using Thumbprint will see these icon constants but will not have the underlying assets. That makes it useless for general use case. Perhaps we should consider adding assets here or moving this out of Thumbprint.

**Comment by dwroth** [comment]
> > @Abdul-Moiz the icons themselves aren't public. That's why you have to log in via okta to see them on thumbprint.design
> 
> That is my concern that someone using Thumbprint will see these icon constants but will not have the underlying assets. That makes it useless for general use case. Perhaps we should consider adding assets here or moving this out of Thumbprint.

It's really only a concern if we are open sourcing the code with the expectation that other people/teams are using it to style their own apps, which isn't the case.  Per our open sourcing policy: "There are many reasons why one might choose to open-source a project, but the primary reason for publishing most Thumbtack projects as open-source is to serve as a recruiting tool by showcasing the range of work being done at Thumbtack."

**Pull request merged**
